#string program
my_string = '''HARSHITHA'''
print(my_string[0])
print(my_string[1])
print(my_string[0:6])
print(my_string[0:5])
print(my_string[0:4])
print(my_string[0:3])
print(my_string[0:2])
print(my_string[0:1])
print(my_string[1])
print(my_string[2])
print(my_string[3])
print(my_string[4])
print(my_string[5])
print(my_string[6])
